-- ============================================================
-- Spotify Listening Analysis
-- Block 2: Intermediate SQL Analysis
-- ============================================================


-- 1. Calculate the percentage of all plays that were skipped.

SELECT 
	  round(100 * COUNT(*) FILTER (WHERE skipped = TRUE)::numeric / COUNT(*), 2) AS skip_rate
FROM spotify_history;


-- 2. Measure the share of total plays generated by the Top 10 most-played tracks.

WITH top_10_tracks AS (
  	SELECT 
    		track_name, 
    		artist_name, 
    		COUNT(*) as play_count 
  	FROM spotify_history
  	Group BY track_name, artist_name
  	ORDER BY play_count DESC
  	LIMIT 10
)

SELECT 
	  ROUND(100 * SUM(play_count)::numeric / (SELECT COUNT(*) FROM spotify_history), 2) AS top_10_share
FROM top_10_tracks;


-- 3. Calculate the average number of unique tracks per artist.

WITH tracks_per_artist as (
  	SELECT 
    		artist_name,
    		COUNT(DISTINCT track_name) as tracks_count
  	FROM spotify_history
  	GROUP BY artist_name
)

SELECT 
	  ROUND(AVG(tracks_count), 2) as avg_tracks_per_artist
FROM tracks_per_artist;


-- 4. Find artists whose average listening time exceeds 2 minutes per play.

SELECT 
  	artist_name,
  	ROUND(AVG(ms_played) / 60000, 2) AS avg_listening_minutes
FROM spotify_history
GROUP BY artist_name
HAVING AVG(ms_played) > 120000
ORDER BY avg_listening_minutes DESC;


-- 5. Find the tracks with the highest total listening time among those played at least 5 times.

WITH track_stats AS (
    SELECT
        track_name,
        artist_name,
        SUM(ms_played) AS total_listening_ms,
        COUNT(*) AS play_count
    FROM spotify_history
    GROUP BY track_name, artist_name
)

SELECT
    track_name,
    artist_name,
    ROUND(total_listening_ms / 60000.0, 2) AS total_listening_minutes
FROM track_stats
WHERE play_count >= 5
ORDER BY total_listening_minutes DESC;


-- 6. Compare platforms by Skip Rate.

SELECT 
  	platform, 
  	round(100 * COUNT(*) FILTER (WHERE skipped = TRUE)::numeric / COUNT(*), 2) AS skip_rate
FROM spotify_history
GROUP BY platform
ORDER BY skip_rate DESC;


-- 7. Find tracks played at least 50 times with the lowest average listening time.

SELECT
    track_name,
    artist_name,
    COUNT(*) AS play_count,
    ROUND(AVG(ms_played) / 60000, 2) AS avg_listening_minutes
FROM spotify_history
GROUP BY track_name, artist_name
HAVING COUNT(*) >= 50
ORDER BY avg_listening_minutes DESC;


-- 8. Rank artists with at least 5 unique tracks by total listening time.

SELECT
    artist_name,
    COUNT(distinct track_name) AS tracks_count,
    ROUND(SUM(ms_played) / 60000.0, 2) AS total_listening_minutes
FROM spotify_history
GROUP BY artist_name
HAVING COUNT(distinct track_name) >= 5
ORDER BY total_listening_minutes DESC;


-- 9. Compare platforms with at least 1,000 plays by their average listening time.

SELECT
    platform,
    COUNT(*) AS play_count,
    ROUND(AVG(ms_played) / 60000, 2) AS avg_listening_minutes
FROM spotify_history
GROUP BY platform
HAVING COUNT(*) >= 1000
ORDER BY avg_listening_minutes DESC;


-- 10. Find the most common reason_start → reason_end combinations.

SELECT
    reason_start,
    reason_end,
    COUNT(*) AS reason_count
FROM spotify_history
GROUP BY reason_start, reason_end
ORDER BY reason_count DESC;
