-- ============================================================
-- Spotify Listening Analysis
-- Block 3: Advanced SQL Analysis
-- ============================================================


-- 1. Identify the most popular track for each artist.

WITH track_plays AS (
    SELECT
        artist_name,
        track_name,
        COUNT(*) AS play_count
    FROM spotify_history
    GROUP BY artist_name, track_name
),

track_ranks AS (
    SELECT
        artist_name,
        track_name,
        play_count,
        RANK() OVER (
            PARTITION BY artist_name
            ORDER BY play_count DESC
        ) AS track_rank
    FROM track_plays
)

SELECT
    artist_name,
    track_name,
    play_count
FROM track_ranks
WHERE track_rank = 1
ORDER BY play_count DESC;


-- 2. Analyze the top 5 artists by play count for each year.

WITH artist_plays AS (
    SELECT
        EXTRACT(YEAR FROM ts) AS year,
        artist_name,
        COUNT(*) AS play_count
    FROM spotify_history
    GROUP BY year, artist_name
),

artist_ranks AS (
    SELECT
        year,
        artist_name,
        play_count,
        RANK() OVER (
            PARTITION BY year
            ORDER BY play_count DESC
        ) AS artist_rank
    FROM artist_plays
)

SELECT
    year,
    artist_name,
    play_count,
    artist_rank
FROM artist_ranks
WHERE artist_rank <= 5
ORDER BY year, artist_rank;


-- 3. Calculate the listening period between the first and last play for each artist.

WITH artist_listening_period AS (
    SELECT
        artist_name,
        FIRST_VALUE(ts) OVER (
            PARTITION BY artist_name
            ORDER BY ts
        ) AS first_listening,
        LAST_VALUE(ts) OVER (
            PARTITION BY artist_name
            ORDER BY ts
            ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING
        ) AS last_listening
    FROM spotify_history
)

SELECT DISTINCT
    artist_name,
    last_listening - first_listening AS listening_period
FROM artist_listening_period
ORDER BY listening_period DESC;


-- 4. Calculate the cumulative number of plays throughout each year.

WITH daily_plays AS (
    SELECT
        EXTRACT(YEAR FROM ts) AS year,
        ts::date AS day,
        COUNT(*) AS play_count
    FROM spotify_history
    GROUP BY year, day
)

SELECT
    day,
    SUM(play_count) OVER (
        PARTITION BY year
        ORDER BY day
    ) AS cumulative_plays
FROM daily_plays
ORDER BY day;


-- 5. Find the month with the most plays for each year.

WITH monthly_plays AS (
    SELECT
        EXTRACT(YEAR FROM ts) AS year,
        EXTRACT(MONTH FROM ts) AS month,
        COUNT(*) AS play_count
    FROM spotify_history
    GROUP BY year, month
),

month_ranks AS (
    SELECT
        year,
        month,
        play_count,
        RANK() OVER (
            PARTITION BY year
            ORDER BY play_count DESC
        ) AS month_rank
    FROM monthly_plays
)

SELECT
    year,
    month,
    play_count
FROM month_ranks
WHERE month_rank = 1
ORDER BY year, month;


-- 6. Analyze the 30-day rolling average of daily plays and its trend.

WITH daily_plays AS (
    SELECT
        ts::date AS day,
        COUNT(*) AS play_count
    FROM spotify_history
    GROUP BY day
)

SELECT
    day,
    play_count,
    AVG(play_count) OVER (
        ORDER BY day
        ROWS BETWEEN 29 PRECEDING AND CURRENT ROW
    ) AS rolling_30_day_avg
FROM daily_plays
ORDER BY day;


-- 7. Analyze the annual change in play count compared with the previous year.

WITH yearly_plays AS (
    SELECT
        EXTRACT(YEAR FROM ts) AS year,
        COUNT(*) AS play_count
    FROM spotify_history
    GROUP BY year
),

plays_with_previous AS (
    SELECT
        year,
        play_count,
        LAG(play_count) OVER (
            ORDER BY year
        ) AS previous_play_count
    FROM yearly_plays
)

SELECT
    year,
    play_count - previous_play_count AS play_count_change
FROM plays_with_previous;


-- 8. Determine the artists with the longest breaks between plays.

WITH listening_intervals AS (
    SELECT
        artist_name,
        ts,
        LAG(ts) OVER (
            PARTITION BY artist_name
            ORDER BY ts
        ) AS previous_listening
    FROM spotify_history
)

SELECT
    artist_name,
    ts - previous_listening AS listening_gap
FROM listening_intervals
WHERE previous_listening IS NOT NULL
ORDER BY listening_gap DESC;


-- 9. Calculate the share of total plays generated by the top 20% of artists.

WITH artist_plays AS (
    SELECT
        artist_name,
        COUNT(*) AS play_count
    FROM spotify_history
    GROUP BY artist_name
),

artist_ranks AS (
    SELECT
        artist_name,
        play_count,
        RANK() OVER (
            ORDER BY play_count DESC
        ) AS artist_rank
    FROM artist_plays
),

top_20_percent AS (
    SELECT
        artist_name,
        play_count
    FROM artist_ranks
    WHERE artist_rank <= (
        SELECT COUNT(*) * 0.2
        FROM artist_plays
    )
)

SELECT
    ROUND(
        100 * SUM(play_count)::numeric /
        (SELECT SUM(play_count) FROM artist_plays),
        2
    ) AS top_20_share
FROM top_20_percent;


-- 10. Determine the number of top artists needed to account for 50% of all plays.

WITH artist_plays AS (
    SELECT
        artist_name,
        COUNT(*) AS play_count
    FROM spotify_history
    GROUP BY artist_name
),

artist_shares AS (
    SELECT
        artist_name,
        play_count,
        ROUND(
            100.0 * play_count /
            (SELECT COUNT(*) FROM spotify_history),
            2
        ) AS play_share
    FROM artist_plays
),

cumulative_artist_shares AS (
    SELECT
        artist_name,
        play_count,
        play_share,
        SUM(play_share) OVER (
            ORDER BY play_share DESC
        ) AS cumulative_share,
        ROW_NUMBER() OVER (
            ORDER BY play_share DESC
        ) AS artist_number
    FROM artist_shares
)

SELECT
    artist_name
FROM cumulative_artist_shares
WHERE artist_number <= (
    SELECT MIN(artist_number)
    FROM cumulative_artist_shares
    WHERE cumulative_share >= 50
)
ORDER BY cumulative_share ASC;


-- 11. Determine the tracks with the largest increase in plays compared with their previous listening day.

WITH daily_track_plays AS (
    SELECT
        ts::date AS day,
        artist_name,
        track_name,
        COUNT(*) AS play_count
    FROM spotify_history
    GROUP BY day, artist_name, track_name
),

track_play_changes AS (
    SELECT
        day,
        artist_name,
        track_name,
        play_count - LAG(play_count) OVER (
            PARTITION BY artist_name, track_name
            ORDER BY day
        ) AS play_count_change
    FROM daily_track_plays
)

SELECT
    day,
    artist_name,
    track_name,
    play_count_change
FROM track_play_changes
WHERE play_count_change IS NOT NULL
ORDER BY play_count_change DESC;


-- 12. Analyze the average number of plays per active day and identify artists with the highest listening intensity.

WITH daily_artist_plays AS (
    SELECT
        ts::date AS day,
        artist_name,
        COUNT(*) AS play_count
    FROM spotify_history
    GROUP BY day, artist_name
),

artist_activity AS (
    SELECT
        artist_name,
        COUNT(*) OVER (
            PARTITION BY artist_name
        ) AS active_days,
        SUM(play_count) OVER (
            PARTITION BY artist_name
        ) AS total_plays
    FROM daily_artist_plays
)

SELECT DISTINCT
    artist_name,
    active_days,
    total_plays,
    ROUND(
        total_plays::numeric / active_days,
        2
    ) AS plays_per_active_day
FROM artist_activity
ORDER BY plays_per_active_day DESC;


-- 13. Analyze track concentration among the top 100 artists by play count

WITH track_plays AS (
    SELECT
        artist_name,
        track_name,
        COUNT(*) AS play_count
    FROM spotify_history
    GROUP BY artist_name, track_name
),

artist_plays AS (
    SELECT
        artist_name,
        SUM(play_count) AS total_plays
    FROM track_plays
    GROUP BY artist_name
),

artist_ranks AS (
    SELECT
        artist_name,
        total_plays,
        RANK() OVER (
            ORDER BY total_plays DESC
        ) AS artist_rank
    FROM artist_plays
),

top_100_artist_tracks AS (
    SELECT
        t.artist_name,
        t.track_name,
        t.play_count,
        a.total_plays,
        ROUND(
            100.0 * t.play_count / a.total_plays,
            2
        ) AS track_share
    FROM track_plays t
    JOIN artist_ranks a
        ON t.artist_name = a.artist_name
    WHERE a.artist_rank <= 100
),

track_ranks AS (
    SELECT
        artist_name,
        track_name,
        play_count,
        track_share,
        RANK() OVER (
            PARTITION BY artist_name
            ORDER BY play_count DESC
        ) AS track_rank
    FROM top_100_artist_tracks
)

SELECT
    artist_name,
    track_name,
    play_count,
    track_share
FROM track_ranks
WHERE track_rank = 1
ORDER BY track_share DESC;
